// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-06-19 15:14:26.516777 +0800 CST m=+0.048340692

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "2501701317@qq.com"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/del": {
            "post": {
                "description": "删除指定图片",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除指定图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片编号id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/list/path": {
            "post": {
                "description": "按指定路径查询图片列表",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "按指定路径查询图片列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片路径,可以使用*通配符",
                        "name": "path",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/list/remark": {
            "post": {
                "description": "按图片备注查询",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "按图片备注查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片备注信息,可以使用*通配符",
                        "name": "remark",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/list/url": {
            "post": {
                "description": "按指定图片源地址查询",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "按指定图片源地址查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片源地址",
                        "name": "img",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/list/url/bytime": {
            "post": {
                "description": "按起止时间获取源地址清单",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "按起止时间获取源地址清单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始日期，格式yyyy-MM-dd，默认为当天",
                        "name": "beginDate",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "结束日期，格式yyyy-MM-dd，默认为明天",
                        "name": "endDate",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pic": {
            "get": {
                "description": "获取限定文件大小的图片",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取限定文件大小的图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图片编号id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "图片大小上限，单位为kb，默认为最大10Mb",
                        "name": "maxSize",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/qua/upload": {
            "post": {
                "description": "上传生意宝资质图片",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "上传生意宝资质图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件数据",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "生意宝账号",
                        "name": "accountId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "资质图片类型",
                        "name": "picType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "银行卡号码，若是传银行卡正面照片时必填",
                        "name": "bankCardNo",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/qua/upload/all": {
            "get": {
                "description": "全部生意宝资质上传到Zimg服务器",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "全部生意宝资质上传到Zimg服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "起始生意宝账户ID",
                        "name": "start",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/qua/upload/from": {
            "post": {
                "description": "单个生意宝资质上传到Zimg服务器",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "单个生意宝资质上传到Zimg服务器",
                "parameters": [
                    {
                        "type": "string",
                        "description": "生意宝账户ID",
                        "name": "accountId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "上传图片",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "上传图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件数据",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图片路径",
                        "name": "path",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "图片备注信息",
                        "name": "remark",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "本地图片文件名",
                        "name": "fileName",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload/from": {
            "post": {
                "description": "转存网络图片到Zimg图床",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "转存网络图片到Zimg图床",
                "parameters": [
                    {
                        "type": "string",
                        "description": "网络图片URL",
                        "name": "imgUrl",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件路径",
                        "name": "path",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "图片备注描述",
                        "name": "remark",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0(zimg-go)",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
